#!/bin/env tclsh

proc scan_dir {dir} {
    puts "scan: ${dir}"

    foreach object [glob -nocomplain -directory ${dir} -type f *] {
	set is_link [catch {file link ${object}}]
	if {${is_link} != 0} {puts "file: ${object}"}
    }

    foreach object [glob -nocomplain -directory ${dir} -type d *] {
	set is_link [catch {file link ${object}}]
	if {${is_link} != 0} {catch {scan_dir ${object}}}
    }
}

if {[llength ${argv}] > 1} {
    set dest [lindex ${argv} end]
    set src [lrange ${argv} 0 end-1]
    
    foreach directory ${src} {scan_dir ${directory}}
} else {
    puts "ddd src1 src2 ... dest"
}
